name: Deploy Vite build to user.github.io

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # or your preferred version

      - name: Install dependencies
        run: npm ci

      - name: Build Vite project
        run: npm run build

      - name: Deploy to user.github.io deployment branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          external_repository: user/Anukesh.github.io
          publish_branch: deployment
          publish_dir: ./dist
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
